[package]
name = "validators"
version = "0.0.1"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
utils = { path = "../utils" }
async-trait = "0.1"
