[package]
name = "orchestrator"
version = "0.0.1"
edition = "2021"

# No external runtime dependencies required for P1 scaffolding

[dependencies]
serde_json = { workspace = true }
validators = { path = "../validators" }

